name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test -race ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: make build
